// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgI8Z5aPOy09p5sjbfYuAz7Asu8Q5tz4c',
    appId: '1:606974339900:web:02216585378203ad61cc39',
    messagingSenderId: '606974339900',
    projectId: 'socialapp-c973c',
    authDomain: 'socialapp-c973c.firebaseapp.com',
    storageBucket: 'socialapp-c973c.appspot.com',
    measurementId: 'G-ECGMWHNN51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE4UUrgzMldVIOg7u6WrnfslyfuxEREEc',
    appId: '1:606974339900:android:5ffde8fc78b5e12261cc39',
    messagingSenderId: '606974339900',
    projectId: 'socialapp-c973c',
    storageBucket: 'socialapp-c973c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_J8eEK_TbT64pYJasKOtjTFzR4nM9uNc',
    appId: '1:606974339900:ios:8f53384475e835fe61cc39',
    messagingSenderId: '606974339900',
    projectId: 'socialapp-c973c',
    storageBucket: 'socialapp-c973c.appspot.com',
    iosClientId: '606974339900-dgueej8eu7rtn9nku2a2t5a4701kla9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_J8eEK_TbT64pYJasKOtjTFzR4nM9uNc',
    appId: '1:606974339900:ios:8f53384475e835fe61cc39',
    messagingSenderId: '606974339900',
    projectId: 'socialapp-c973c',
    storageBucket: 'socialapp-c973c.appspot.com',
    iosClientId: '606974339900-dgueej8eu7rtn9nku2a2t5a4701kla9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
